### PR TITLE
Revert "Add DevicePerformanceSettingsHelper"

### PR DESCRIPTION
**Pull request by ghost**
Possibly a simpler and a cleaner solution: https://github.com/namagi/android_packages_apps_Settings/commit/c698ddf7fc23083615729f768e01b50a5d7430e2

unfortunately I can't make a pull request for that as there is no Seetings project on razrqcom.
The above mentioned solution seems simpler and avoids adding an extra apk to the system.

Also, that patch by Emerson requires a device to be rebooted for the thermal_max_freq and scaling_max_freq to be in sync which is really a bad requirement for scaling frequencies.
Need for superuer access is also not needed.

### CODE REVIEW

**Comment by ghost** [comment]
thermald.conf is still unpatched. Probably will remain like that.
Essentially, the rationale behind this is I hope that mess between thermald and overclock is a torn in the eye which will finally be resolved so we can have a working overclock (as much as thermald.conf permits :-P)

**Comment by SkrilaxCZ** [comment]
As of now, we don't want to patch Settings (and require a fork), so the commit would have to be upstream mergeable, which it isn't.

The DevicePerformanceSettingsHelper is to fix the issues with performance settings (make thermald respect user settings and pass the settings to CPU1 as well).

Overclock was reverted (at least for now, because CPU bootup frequency needs patching, thermald needs some patching etc.).

**Comment by ghost** [comment]
right, I forgot about cpu1. This still seems complicated when it shouldn't be. The main problem with Emersons patch is that it needs a reboot for thermald and scaling max to be in sync.
Close this?

Btw., overclock wasn't reverted, just disabled by config.

**Comment by SkrilaxCZ** [comment]
I think it reacts on system settings change as well (and restarts thermald in such case). Anyway yeah, closing.

**Comment by ghost** [comment]
It doesn't react on system settings change. You need to reboot for it to tale effect.
Just out of curiosity, why not fork Settings? Would have some negative implications?

**Comment by SkrilaxCZ** [comment]
You're correct, it doesn't react on settings change.

Let's keep the forks at minimum (as when CM for our devices will get official, official builds will not have that included - and device repos have to remain compatible with both). I submited a patch to CM (to externalize the governor settings, so the information written can be sent to some app or smth like that). Or if you have a better solution, you can submit it to CM directly.

**Comment by epinter** [comment]
The thermal_max it's not present on all the phones, so I doubt such a
change on settings will be accepted. Better keep it on phone's device tree.
I don't like the idea of a service be restarted every time user make a
change on frequency, can cause problems if there's a bug in the ui code...
I prefer the overclock to be setup only on boot. Overclock is a hack and
will never be for everyone, many phones crashes with frequencies higher
then stock.
Personally, I hate overclock my phone, useless... But as a developer, I
need to develop overclock and support users that like overclock, but
without cause instability.

2013/6/15 Martin notifications@github.com

**Comment by ghost** [comment]
Good point, indeed. I personally did not notice any significant difference between 1512mhz and 2ghz, especially for "common", day-to-day tasks. Tried to OC out of curiosity (but it turned out to be complicated).

Since need for a reboot is uncommon when changing freqs, it might be a good idea to inform users of the reqirement (if overclock is ever enabled again).

**Comment by dhacker29** [comment]
An on change listener can probably be added to restart thermald on change

**Pull request closed without merging**
